export const FILTER_SET_PRICE = 'FILTER_SET_PRICE'
export const FILTER_SET_CATEGORY = 'FILTER_SET_CATEGORY'
export const FILTER_SET_CATEGORY_LIST = 'FILTER_SET_CATEGORY_LIST'
export const FILTER_SET_AVAILABLE = 'FILTER_SET_AVAILABLE'
